### ISSUE TITLE
Error on isntall

### ISSUE THREAD

**Issue by krovaxpc** [PluginsOCSInventory-NG/defaultwindowsapp#3]
Good day,

Install plugin show error:
ERROR: check if Map.pm and defaultwindowsapp.conf exist

in files is this name: defaultapp.conf

in file: install.php  i msut change defaultapp to defaultwindowsapp

<?php

function extension_install_defaultwindowsapp()
{
    
     $commonObject = new ExtensionCommon;

     $commonObject -> sqlQuery("DROP TABLE `defaultapp`");

     $commonObject -> sqlQuery("CREATE TABLE `defaultapp`(
                                `ID` INT(11) NOT NULL AUTO_INCREMENT,
                                `HARDWARE_ID` INT (11) NOT NULL,
                                `NAME` VARCHAR(255) DEFAULT NULL,
                                `TYPE` VARCHAR(255) DEFAULT NULL,
                                PRIMARY KEY (`ID`, `HARDWARE_ID`)
                                ) ENGINE=INNODB ;"); 
     
}

function extension_delete_defaultwindowsapp()
{
    $commonObject = new ExtensionCommon;
    
    $commonObject -> sqlQuery("DROP TABLE `defaultapp`");
}

function extension_upgrade_defaultwindowsapp()
{

}

After that i cant be installed, bud i dont think its working.

**Comment by BMTTeam** [comment]
I confirm that renaming defaultapp to defaultwindowsapp did the trick and the plugin is now installed
